namespace ReCommon
{
    public class CommonBarCode
    {
        public enum BarYear
        {
            A,//2016
            B,//2017
            C,//2018
            D,//2019
            E,//2020
            F,//2021
            G,//2022
            H,//2023
            I,//2024
            J,//2025
            K,
            L,
            M,
            N,
            O,
            P,
            Q,
            R,
            S
        }
        public enum BarMonth
        {
            A,//一月
            B,//二月
            C,//三月
            D,//四月
            E,//五月
            F,//六月
            G,//七月
            H,//八月
            I,//九月
            J,//十月
            K,//十一月
            L//十二月
        }
        public enum BarDay
        {
            A,//一
            B,//二
            C,//三
            D,//四
            E,//五
            F,//六
            G,//七
            H,//八
            I,//九
            J,//十
            K,//十一
            L,//十二
            M,//十三
            N,//十四
            O,//十五
            P,//十六
            Q,//十七
            R,//十八
            S,//十九
            T,//二十
            U,//二十一
            V,//二十二
            W,//二十三
            X,//二十四
            Y,//二十五
            Z,//二十六
            a,//二十七
            b,//二十八
            c,//二十九
            d,//三十
            e//三十一
        } 
    }
}
